data:
  dedup: True
  subset: False
  subset_size: 22000 # 22000
  chunk_size_lines: 10000
  chunk_name_size: 55
  valid_split: 0.1
  # 13200000 / chunk_size_lines / 26 =~ chunk_name_size

vocab:
  size: 30000
  min_frequency: 2
  lowercase: True

seed: 42

training:
  max_seq_length: 128 # 512

  max_predictions_per_seq: 20
  masked_lm_prob: 0.10
  whole_word_masking: True
  num_train_steps: 1000 # 125000
  num_warmup_steps: 100 # 3125
  epochs: 1 # used only if num_train_steps <= 0, otherwise autocalculated
  save_checkpoints_steps: 200

  weight_decay: 0.0
  learning_rate: 5e-5
  adam_epsilon: 1e-8
  max_grad_norm: 1.0

defaults:
  - model: tiny
  - hydra/job_logging: colorlog

hydra:
  run:
    dir: run
