data:
  valid_split: 0.04

vocab:
  max_size: 30000
  lowercase: True

seed: 42

training:
  max_seq_length: 512
  masked_lm_prob: 0.10
  weight_decay: 0.0
  learning_rate: .00176

defaults:
  - model: tiny
  - hydra/job_logging: colorlog

hydra:
  run:
    dir: run
