data:
  dedup: True
  subset: False
  subset_size: 22000
  valid_split: 0.04
  processing_minibatch_size: 10000

vocab:
  max_size: 30000
  min_frequency: 2
  lowercase: True

seed: 42

training:
  machine_type: v100

  max_seq_length: 128

  masked_lm_prob: 0.10
  num_train_steps: 125000 #1000 # 125000
  num_warmup_steps: 3125 # 100 # 3125
  epochs: 1 # used only if num_train_steps <= 0, otherwise autocalculated

  weight_decay: 0.0
  learning_rate: .00176
  max_grad_norm: 1.0

defaults:
  - model: tiny
  - hydra/job_logging: colorlog

hydra:
  run:
    dir: run
