name: Build and test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.5
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv
        pipenv install --dev
        pipenv shell
    - name: Lint
      run: make lint
    - name: Test
      run: make test
